// Merges the asset manifests into js/data.js so the film also runs from file://
// Usage: node tools/build-data.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => {
  const f = join(root, p);
  if (!existsSync(f)) return [];
  try { return JSON.parse(readFileSync(f, 'utf8')); } catch (e) { console.warn('skip', p, e.message); return []; }
};
const keep = (m) => existsSync(join(root, m.file));

// Per-image presentation overrides (low-res portraits get the archival-print treatment)
const overrides = JSON.parse(readFileSync(join(root, 'assets/data/overrides.json'), 'utf8'));

const images = [...read('assets/data/images-a.json'), ...read('assets/data/images-b.json'), ...read('assets/data/images-c.json'), ...read('assets/data/images-d.json')]
  .filter(keep)
  .map((m) => ({ ...m, ...(overrides[m.id] || {}) }));
const videos = read('assets/data/videos.json').filter(keep);
// AI-generated b-roll dropped into assets/video/generated/ (see SHOTLIST.md): always labelled on screen
const generated = read('assets/data/generated.json').filter(keep).map((m) => ({ ...m, synthetic: true }));
const now2026 = read('assets/data/now-2026.json');

const out = `/* Generated by tools/build-data.mjs: do not edit by hand. */\nwindow.FILM_DATA = ${JSON.stringify({ images, videos: [...videos, ...generated], now2026 }, null, 1)};\n`;
writeFileSync(join(root, 'js/data.js'), out);
console.log(`images ${images.length} · videos ${videos.length} · generated ${generated.length} · 2026 items ${now2026.length}`);
